# Generated by Django 5.1.3 on 2024-11-17 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='limit',
            old_name='amount',
            new_name='limit',
        ),
    ]
