# Generated by Django 5.1.3 on 2024-11-18 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karz', '0002_rename_amount_limit_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='limit',
        ),
    ]
