# Generated by Django 5.1.3 on 2024-11-18 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karz', '0003_remove_loan_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='limit',
            old_name='limit',
            new_name='limit_amount',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='amount',
            new_name='loan_amount',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='payment_amount',
        ),
    ]
